# FOOD REF
POST http://localhost:5000/foodrefs
Content-Type: application/json

{
    "original_calory": 80,
    "original_quantity": 55,
    "name": "riz blanc"
}

###

POST http://localhost:5000/foodrefs
Content-Type: application/json

{
    "original_calory": 100,
    "original_quantity": 1,
    "name": "barre tendre kirkland"
}

###

POST http://localhost:5000/foodrefs
Content-Type: application/json

{
    "original_calory": 100,
    "original_quantity": 80,
    "quantity_type": "grammes",
    "name": "homard"
}

###
POST http://localhost:5000/foodrefs
Content-Type: application/json

{
    "original_calory": 100,
    "original_quantity": 80,
    "quantity_type": "grammes",
    "name": "dfsdsf"
}

###

POST http://localhost:5000/foodrefs
Content-Type: application/json

{
    "original_calory": 125,
    "original_quantity": 4,
    "quantity_type": "tranches",
    "name": "jambon"
}

###

PUT http://localhost:5000/foodrefs/2
Content-Type: application/json

{
    "original_calory": 80,
    "original_quantity": 55,
    "name": "riz"
}

###

GET http://localhost:5000/foodrefs

###

GET http://localhost:5000/foodrefs/6
###

# FOOD JOURNAL ENTRY

POST http://localhost:5000/food-journal-entry
Content-Type: application/json

{   
    "date": "2023-05-31T15:11:14.198Z",
    "quantity": 56,
    "quantity_type": "morceaux",
    "calories": 250,
    "thoughts": "je me sens bien aujourd'hui",
    "journal_category": {
        "id":1,
        "name":"food"
    },
    "food_ref": {
        "name": "etoile",
        "original_calory": 80,
        "original_quantity": 55
        },
    "name": "riz blanc"
}

###
POST http://localhost:5000/food-journal-entry
Content-Type: application/json

{   
    "date": "2023-05-29T15:11:14.198Z",
    "quantity": 56,
    "quantity_type": "morceaux",
    "calories": 250,
    "thoughts": "je me sens bien aujourd'hui",
    "journal_category": {
        "id":1,
        "name":"food"
    },
    "food_ref": null,
    "name": "riz blanc"
}

### 
POST http://localhost:5000/food-journal-entry
Content-Type: application/json

{   
    "date": "2023-05-29T15:11:14.198Z",
    "quantity": 34,
    "quantity_type": "carré",
    "calories": 345,
    "thoughts": "je me sens bien bien bien aujourd'hui",
    "journal_category": {
        "id":1,
        "name":"food"
    },
    "name":"pain au chocolat"
}

###
POST http://localhost:5000/food-journal-entry
Content-Type: application/json

{   
    "date": "2023-05-29T15:11:14.198Z",
    "quantity": 34,
    "quantity_type": "grammes",
    "calories": 345,
    "thoughts": "ehlala",
    "journal_category": {
        "id":1,
        "name":"food"
    },
    "name":"Caprice des dieux"
}

###
GET http://localhost:5000/food-journal-entries/

###
GET http://localhost:5000/food-journal-entries/date?date=2023-05-28

###

# JOURNAL CATEGORY

POST http://localhost:5000/journal-category
Content-Type: application/json

{
    "name":"food"
}

###

GET http://localhost:5000/journal-category/1

###

GET http://localhost:5000/journal-categories

